networks: {}
services:
  backend:
    build: .
    ports:
    - "3000:8080"
    expose:
    - "8080"
  frontend:
    build: ./website_files/.
    entrypoint:
    - node
    - /website_files/server.js
    volumes:
    - ./website_files:/website_files
    ports:
    - "80:5000"
version: "2"
